// Re-export the generated code so client/server can use "common::snpguard::..."
pub mod snpguard {
    // Include protobuf messages generated by prost (gRPC service traits not used)
    tonic::include_proto!("snpguard");
    
    // Also export message types for use without gRPC (e.g., HTTP endpoints)
    pub use prost::Message;
}
