// Re-export the generated code so client/server can use "common::snpguard::..."
pub mod snpguard {
    // Include protobuf messages and gRPC service definitions generated by tonic-build
    // tonic-build generates both the service traits and the message types
    tonic::include_proto!("snpguard");
    
    // Also export message types for use without gRPC (e.g., HTTP endpoints)
    pub use prost::Message;
}
